### ISSUE TITLE
Importing fails for python3 on Windows

### ISSUE THREAD

**Issue by oconnor663** [tartley/colorama#22]
Tried on both Windows 7 and Windows 8.1. Importing colorama works fine in python2.7, but not in python3.4, where it gives this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\cygwin64\tmp\colorama\colorama\__init__.py", line 2, in <module>
    from .initialise import init, deinit, reinit
  File "C:\cygwin64\tmp\colorama\colorama\initialise.py", line 5, in <module>
    from .ansitowin32 import AnsiToWin32
  File "C:\cygwin64\tmp\colorama\colorama\ansitowin32.py", line 7, in <module>
    from .winterm import WinTerm, WinColor, WinStyle
  File "C:\cygwin64\tmp\colorama\colorama\winterm.py", line 2, in <module>
    from . import win32
  File "C:\cygwin64\tmp\colorama\colorama\win32.py", line 89, in <module>
    wintypes.c_char_p
AttributeError: 'module' object has no attribute 'c_char_p'
```
